version: '3'
services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:12
    container_name: nfs_server
    privileged: true
    restart: unless-stopped
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - /data/nfs-storage:/data
    ports:
      - 2049:2049
    
      
      
    
