version: '3'
services:
  nfs:
    image: erichough/nfs-server
    container_name: nfs_server
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./exports.txt:/etc/exports:ro
      - ./data:/data
    
    ports:
      - 2049:2049
    
