services:
  docker-registry:
    image: registry:3
    container_name: docker-registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./config/docker.yml:/etc/docker/registry/config.yml:ro
      - docker_data:/var/lib/registry
    networks:
      - local-registry

  quay-registry:
    image: registry:3
    container_name: quay-registry
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - ./config/quay.yml:/etc/docker/registry/config.yml:ro
      - quay_data:/var/lib/registry
    networks:
      - local-registry

  ghcr-registry:
    image: registry:3
    container_name: ghcr-registry
    restart: unless-stopped
    ports:
      - "5002:5000"
    volumes:
      - ./config/ghcr.yml:/etc/docker/registry/config.yml:ro
      - ghcr_data:/var/lib/registry
    networks:
      - local-regi\stry

volumes:
  docker_data:
  ghcr_data:
  quay_data:

networks:
  local-registry:
    name: local-registry
    driver: bridge