services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=lampac-network"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      # Let's Encrypt configuration
      - "--certificatesresolvers.le.acme.email=vladoz77@yandex.ru"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
    labels:
      # Enable self‑routing
      - "traefik.enable=true"
      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.kz.home-local.site`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls.certresolver=le"
      # Basic‑auth middleware
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$apr1$$CmiVRFjs$$bPQcSgQ.2HcTzM.HVTvAl1"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
    networks:  
      - lampac-network 
  lampac:
    image: immisterio/lampac
    container_name: lampac
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lampac.rule=Host(`lampa.kz.home-local.site`)"
      - "traefik.http.routers.lampac.entrypoints=websecure"
      - "traefik.http.routers.lampac.tls.certresolver=le"
    ports:
      - "9118"
    volumes:
      - ./init.conf:/home/init.conf
      - ./manifest.json:/home/module/manifest.json
    environment:  
      - TZ=Europe/Moscow  
    networks:  
      - lampac-network  
  
networks:  
  lampac-network:  
