version: 0.1
log:
  level: info
  formatter: json
http:
  addr: :5000
proxy:
  remoteurl: https://registry-1.docker.io
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
