services:
  rtmp-nginx:
    container_name: rtmp-nginx
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:r
      - stream:/usr/share/nginx/html/stream:rw
    ports:
      - 8080:8080
      - 1935:1935
volumes:
  stream: