services:
  traefik:
    image: traefik:${TRAEFIK_VERSION:-latest}
    container_name: ${DOCKER_CONTAINER_NAME:-traefik}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${ROOT_CA_DIR}:/${TRAEFIK_CACERTIFICATE}:ro
      - ./acme:/acme
      - ./config:/etc/traefik
    # Traefik Dynamic configuration via Docker labels
    labels:
      # Enable self‑routing
      - "traefik.enable=true"
      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.home.local`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=homelab"
      # Basic‑auth middleware
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$apr1$$9Bf7fi7r$$4SZtA20rXAYDxGWvP8jFM0"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"
    networks:
      traefik-net:
        ipv4_address: ${TRAEFIK_STATIC_IP}
        # aliases:
        #   - dashboard.home.local

networks:
  traefik-net:
    name: ${DOCKER_NETWORK:-proxy}
    external: true
