services:
  gitlab-init:
    image: alpine:latest
    container_name: gitlab-init
    restart: unless-stopped
    env_file:
      - .env
    command: >
     sh -c "apk add --no-cache gettext &&
     envsubst < /templates/gitlab.rb.template > /etc/gitlab/gitlab.rb &&
     envsubst < /templates/traefik.yml.template > /etc/traefik/traefik.yml &&
     echo 'gitlab.rb and traefik.yml generated successfully'"
    volumes:
    - ./gitlab/gitlab.rb.template:/templates/gitlab.rb.template:ro
    - ./traefik/traefik.yml.template:/templates/traefik.yml.template:ro
    - gitlab_config:/etc/gitlab
    networks:
      - gitlab_net
  
  gitlab:
    image: gitlab/gitlab-ee:%{GITLAB_VERSION:-latest}
    container_name: gitlab
    restart: unless-stopped
    hostname: ${GITLAB_HOSTNAME}
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    shm_size: '256m'

    labels:
      - traefik.enable=true
      # Gitlab router
      - traefik.http.routers.gitlab.rule=Host(`${GITLAB_HOSTNAME}`)
      - traefik.http.routers.gitlab.entrypoints=websecure
      - traefik.http.routers.gitlab.tls=true
      - traefik.http.routers.gitlab.tls.certresolver=le
      - traefik.http.services.gitlab.loadbalancer.server.port=80
      # Ssh router
      - traefik.tcp.routers.gitlab-ssh.entrypoints=ssh
      - traefik.tcp.routers.gitlab-ssh.rule=HostSNI(`*`)
      - traefik.tcp.services.gitlab-ssh.loadbalancer.server.port=22
    networks:
      - gitlab_net
    depends_on:
      gitlab-init:
        condition: service_completed_successfully
  
  traefik:
    image: traefik:${TRAEFIK_VERSION:-latest}
    container_name: traefik
    restart: unless-stopped
    ports:
     - 80:80
     - 443:443
     - 22:22
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    - ./traefik/acme.json:/acme.json
    networks:
      - gitlab_net
    depends_on:
      - gitlab-init

networks:
  gitlab_net:
    name: gitlab_net
    driver: bridge

volumes:
  gitlab_config:
  gitlab_data:
      
