services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_VERSION:-latest}
    container_name: gitlab
    restart: unless-stopped
    hostname: ${GITLAB_HOSTNAME}
    volumes:
      - './gitlab/config:/etc/gitlab:ro'
      - './gitlab/logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    shm_size: '256m'
    labels:
      - traefik.enable=true
      # Gitlab router
      - traefik.http.routers.gitlab.rule=Host(`${GITLAB_HOSTNAME}`)
      - traefik.http.routers.gitlab.entrypoints=websecure
      - traefik.http.routers.gitlab.tls=true
      - traefik.http.routers.gitlab.tls.certresolver=le
      - traefik.http.services.gitlab.loadbalancer.server.port=80
      # Ssh router
      - traefik.tcp.routers.gitlab-ssh.entrypoints=ssh
      - traefik.tcp.routers.gitlab-ssh.rule=HostSNI(`*`)
      - traefik.tcp.services.gitlab-ssh.loadbalancer.server.port=22
    networks:
      - gitlab_net
  
  traefik:
    image: traefik:${TRAEFIK_VERSION:-latest}
    container_name: traefik
    restart: unless-stopped
    ports:
     - 80:80
     - 443:443
     - 2224:2224
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./traefik:/etc/traefik
    networks:
      - gitlab_net

networks:
  gitlab_net:
    name: gitlab_net
    driver: bridge

volumes:
  gitlab_data:
    name: gitlab_data
      
