route:
  receiver: admin

receivers:
- name: admin
  email_configs:
  - to: 'vladoz77@yandex.ru'
    from: 'vladozz23@gmail.com'
    smarthost: 'smtp.gmail.com:465'
    auth_username: vladozz23@gmail.com
    auth_identity: vladozz23@gmail.com
    auth_password: pisxijhlxexflfhu
    send_resolved: true
    require_tls: false

