route:
  receiver: admin

receivers:
- name: admin
  email_configs:
  - to: 'vladoz77@yandex.ru.com'
    from: 'vladozz23@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: vladozz23@gmail.com
    auth_identity: vladozz23@gmail.com
    auth_password: 'Vl@d0z77VK'
