global:
  smtp_from: 'vladozz23@gmail.com'
  smtp_smarthost: smtp.gmail.com:465
  smtp_auth_username: vladozz23@gmail.com
  smtp_auth_identity: vladozz23@gmail.com
  smtp_auth_password: pisxijhlxexflfhu
  smtp_require_tls: false
route:
  receiver: admin
  group_wait: 10s
  group_by: 
    - instance
  routes:
    # linux team
    - receiver: server-admin
      group_wait: 10s
      matchers:
        - app_type=linux
      group_by:
        - category
        - severity
      routes:
      # for critical alert
      - receiver: linux-team-admin
        matchers: 
         - severity=critical
      # for warning alert
      - receiver: linux-team-tp
        matchers: 
         - severity=warning

    # Docker team
    - receiver: server-admin    
      group_wait: 10s
      matchers:
        - app_type=docker
      routes:
        - receiver: docker-team-admin
          matchers:
            - severity=critical
        - receiver: docker-team-tp
          matchers:
            - severity=warning

inhibit_rules:
  - target_match: 
      severity: warning
    source_match:
      severity: critical
    equal:
      - category
    

receivers:
- name: admin
  email_configs:
  - to: 'vladoz77@yandex.ru'
    send_resolved: true

- name: server-admin
  email_configs:
  - to: 'vladoz77@yandex.ru'
    send_resolved: true

# for critical alert in linux
- name: linux-team-admin
  telegram_configs:
  - bot_token: 6542927122:AAG3qDOcXNpKC46hg1pQCf4e0WG50InWg1w
    api_url: https://api.telegram.org
    chat_id: 310164408
    parse_mode: ''

# for warning alert in linux
- name: linux-team-tp
  telegram_configs:
  - bot_token: 5871733943:AAG80rp0SDHGA3D24oVs7JTFa89siIcbNd0
    api_url: https://api.telegram.org
    chat_id: 310164408
    parse_mode: ''

# docker team admin
- name: docker-team-admin
  email_configs:
  - to: 'vladozz23@gmail.com'
    send_resolved: true

# docker team tp
- name: docker-team-tp
  email_configs:
  - to: 'vladozz23@gmail.com'
    send_resolved: true
    

