version: '3'
volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:

networks:
  ngix-manager_default:
    external: true
  prometheus:
  loki:

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    restart: unless-stopped
    command: 
      - --config.file=/etc/prometheus/prometheus.yaml
      - --web.enable-lifecycle
      - --storage.tsdb.path=/prometheus
    environment:
      - TZ=value
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./rules:/etc/prometheus/rules
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    networks:
       prometheus:
       ngix-manager_default:
         ipv4_address: 172.21.0.5
  
  node-exporter:
    image: prom/node-exporter:v1.6.0
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      # - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      prometheus:

  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    ports:
      - 8081:8080
    restart: unless-stopped
    networks:
      prometheus:
    
  grafana:
    image: grafana/grafana:10.0.1
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana:rw
    networks:
      ngix-manager_default:
        ipv4_address: 172.21.0.10
      prometheus:
      loki:

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    restart: unless-stopped
    command: 
      - --config.file=/etc/alertmanager/alertmanager.yaml
    volumes:
      - ./alertmanager.yaml:/etc/alertmanager/alertmanager.yaml:ro
      - alertmanager-data:/data
    ports:
      - 9093:9093
    networks:
      loki:
      ngix-manager_default:
        ipv4_address: 172.21.0.6
      prometheus:
      

    



