version: "3.0"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    privileged: true
    restart: unless-stopped
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
    volumes:
      - ./certs:/certs/client:rw
      - jenkins-data:/var/jenkins_home:rw
    ports:
      - 2376:2376
      - 8080:8080
      - 50000:50000
    networks: 
      jenkins-network:
      nginx_net:
    extra_hosts:
      - oauth.home.local:172.24.0.1
  
  


volumes:
 jenkins-data:

networks:
  jenkins-network:
  nginx_net:
    external: true
      
      

      
  
