version: "3.0"
services:
  jenkins:
    image: jenkins/jenkins:latest-jdk17
    container_name: jenkins
    privileged: true
    restart: unless-stopped
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client:rw
      - jenkins-data:/var/jenkins_home:rw
    ports:
      - 2376:2376
      - 8080:8080
      - 50000:50000
    networks: 
      jenkins-network:
      nginx_net:
    # extra_hosts:
    #   - oauth.dev.local:172.20.69.108
  
  mail:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    networks:
      jenkins-network:
    ports:
        - 1025:1025
        - 8025:8025
  


volumes:
 jenkins-docker-certs:
 jenkins-data:

networks:
  jenkins-network:
  nginx_net:
    external: true
      
      

      
  
