groups:
- name: rule
  rules:
  - record: job:node_cpu_seconds_total:avg_idle
    expr: avg without(cpu)(rate(node_cpu_seconds_total{mode="idle"}[5m]))

  - record: job:node_cpu_seconds_total:avg_not_idle
    expr: avg without(cpu)(rate(node_cpu_seconds_total{mode!="idle"}[5m]))
