auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 16777216 # 16MB
  grpc_server_max_send_msg_size: 16777216 # 16MB
  grpc_server_max_concurrent_streams: 1000

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules

schema_config:
  configs:
  - from: 2020-05-15
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

limits_config:
  retention_period: 168h
  ingestion_rate_mb: 20
  ingestion_burst_size_mb: 20
  max_streams_per_user: 10000
  max_line_size: 256000
  reject_old_samples: true
  reject_old_samples_max_age: 24h
  split_queries_by_interval: 6h

ruler:
  alertmanager_url: http://alertmanager:9093
