# docker-compose.yml
services:
    torrserver:
        image: ghcr.io/yourok/torrserver
        container_name: torrserver
        environment:
            - TS_PORT=8090
            - TS_DONTKILL=1
            - TS_HTTPAUTH=0
            - TS_CONF_PATH=/opt/ts/config
            - TS_TORR_DIR=/opt/ts/torrents
        volumes:
            - 'torrserv_data:/opt/ts/torrents'
            - 'torrserv_data:/opt/ts/config'
        ports:
            - '8090:8090'
        restart: unless-stopped
volumes:
    torrserv_data:
        
