services:
  marzban:
    image: gozargah/marzban:latest
    container_name: marzban
    restart: always
    network_mode: host
    env_file: .env
    volumes:
      - ./marzban/xray_config.json:/var/lib/marzban/xray_config.json
    depends_on:
     - mysql

  mysql:
    image: mysql:lts
    container_name: mysql
    env_file: .env
    restart: always
    network_mode: host
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "marzban", "--password=${MYSQL_PASSWORD}"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - mysql:/var/lib/mysql

  warp:
    container_name: warp_v3
    image: monius/docker-warp-socks:v3
    ports:
      - 40000:9091

volumes:
  mysql:
