services:
  app:
    image: 'jc21/nginx-proxy-manager:2.11.2'
    restart: unless-stopped
    container_name: nginx-proxy-manager
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - data_nginx:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
       nginx_net:
      

volumes:
  data_nginx:

networks:
  nginx_net:
    external: true
      

