version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:2.10.3'
    restart: unless-stopped
    container_name: nginx-proxy-manager
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - data_nginx:/data
    networks:
       ngix_default:
      

volumes:
  data_nginx:
  letsencrypt_nginx:

networks:
  ngix_default:
    name: nginx_default
    ipam:
      config:
        - subnet: "172.50.0.0/24"
          gateway: "172.50.0.1"

